import type { Constituent, IndexSummary } from "./types";

export const fixtureIndexes: IndexSummary[] = [
  {
    code: "MTEU500",
    slug: "magic-europe-500",
    name: "Magic Europe 500",
    game: "Magic: The Gathering",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "YGEU250",
    slug: "yugioh-europe-250",
    name: "Yu-Gi-Oh! Europe 250",
    game: "Yu-Gi-Oh!",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 250,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "OPEU100",
    slug: "one-piece-europe-100",
    name: "One Piece Europe 100",
    game: "One Piece",
    universe: "singles",
    history_start_date: "2026-04-01",
    history_start_kind: "validation",
    base_date: "2026-07-20",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "PKEU250",
    slug: "pokemon-europe-250",
    name: "Pokemon Europe 250",
    game: "Pokemon",
    universe: "singles",
    history_start_date: "2026-04-01",
    history_start_kind: "validation",
    base_date: "2026-07-20",
    status: "accumulating",
    target_size: 250,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "OPEUSLD",
    slug: "one-piece-sealed-pilot",
    name: "One Piece Sealed Pilot",
    game: "One Piece",
    universe: "sealed",
    history_start_date: "2026-04-01",
    history_start_kind: "validation",
    base_date: "2026-07-20",
    status: "accumulating",
    target_size: 25,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "DBSEU100",
    slug: "dragon-ball-super-europe-100",
    name: "Dragon Ball Super Europe 100",
    game: "Dragon Ball Super",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "FABEU100",
    slug: "flesh-and-blood-europe-100",
    name: "Flesh and Blood Europe 100",
    game: "Flesh and Blood",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "DGEU100",
    slug: "digimon-europe-100",
    name: "Digimon Europe 100",
    game: "Digimon",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "LCEU100",
    slug: "disney-lorcana-europe-100",
    name: "Disney Lorcana Europe 100",
    game: "Disney Lorcana",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "SWUEU100",
    slug: "star-wars-unlimited-europe-100",
    name: "Star Wars Unlimited Europe 100",
    game: "Star Wars: Unlimited",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "RBEU100",
    slug: "riftbound-europe-100",
    name: "Riftbound Europe 100",
    game: "Riftbound",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  }
];

export const fixtureConstituents: Record<string, Constituent[]> = Object.fromEntries(
  fixtureIndexes.map((index) => [index.code, []])
);
