import type { Constituent, IndexSummary } from "./types";

export const fixtureIndexes: IndexSummary[] = [
  {
    code: "MTEU500",
    slug: "magic-europe-500",
    name: "Magic Europe 500",
    game: "Magic: The Gathering",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "MTEUSLD",
    slug: "magic-sealed-europe-100",
    name: "Magic Sealed Europe 100",
    game: "Magic: The Gathering",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "YGEU500",
    slug: "yugioh-europe-500",
    name: "Yu-Gi-Oh! Europe 500",
    game: "Yu-Gi-Oh!",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "YGEUSLD",
    slug: "yugioh-sealed-europe-100",
    name: "Yu-Gi-Oh! Sealed Europe 100",
    game: "Yu-Gi-Oh!",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "OPEU500",
    slug: "one-piece-europe-500",
    name: "One Piece Europe 500",
    game: "One Piece",
    universe: "singles",
    history_start_date: "2026-04-01",
    history_start_kind: "validation",
    base_date: "2026-07-20",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "PKEU500",
    slug: "pokemon-europe-500",
    name: "Pokemon Europe 500",
    game: "Pokemon",
    universe: "singles",
    history_start_date: "2026-04-01",
    history_start_kind: "validation",
    base_date: "2026-07-20",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "PKEUSLD",
    slug: "pokemon-sealed-europe-100",
    name: "Pokemon Sealed Europe 100",
    game: "Pokemon",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "OPEUSLD",
    slug: "one-piece-sealed-europe-100",
    name: "One Piece Sealed Europe 100",
    game: "One Piece",
    universe: "sealed",
    history_start_date: "2026-04-01",
    history_start_kind: "validation",
    base_date: "2026-07-20",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "DBSEU500",
    slug: "dragon-ball-super-europe-500",
    name: "Dragon Ball Super Europe 500",
    game: "Dragon Ball Super",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "DBSEUSLD",
    slug: "dragon-ball-super-sealed-europe-100",
    name: "Dragon Ball Super Sealed Europe 100",
    game: "Dragon Ball Super",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "FABEU500",
    slug: "flesh-and-blood-europe-500",
    name: "Flesh and Blood Europe 500",
    game: "Flesh and Blood",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "FABEUSLD",
    slug: "flesh-and-blood-sealed-europe-100",
    name: "Flesh and Blood Sealed Europe 100",
    game: "Flesh and Blood",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "DGEU500",
    slug: "digimon-europe-500",
    name: "Digimon Europe 500",
    game: "Digimon",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "DGEUSLD",
    slug: "digimon-sealed-europe-100",
    name: "Digimon Sealed Europe 100",
    game: "Digimon",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "LCEU500",
    slug: "disney-lorcana-europe-500",
    name: "Disney Lorcana Europe 500",
    game: "Disney Lorcana",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "LCEUSLD",
    slug: "disney-lorcana-sealed-europe-100",
    name: "Disney Lorcana Sealed Europe 100",
    game: "Disney Lorcana",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "SWUEU500",
    slug: "star-wars-unlimited-europe-500",
    name: "Star Wars Unlimited Europe 500",
    game: "Star Wars: Unlimited",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "SWUEUSLD",
    slug: "star-wars-unlimited-sealed-europe-100",
    name: "Star Wars Unlimited Sealed Europe 100",
    game: "Star Wars: Unlimited",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "RBEU500",
    slug: "riftbound-europe-500",
    name: "Riftbound Europe 500",
    game: "Riftbound",
    universe: "singles",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 500,
    breadth: 0,
    volatility_30d: 0,
    history: []
  },
  {
    code: "RBEUSLD",
    slug: "riftbound-sealed-europe-100",
    name: "Riftbound Sealed Europe 100",
    game: "Riftbound",
    universe: "sealed",
    history_start_date: "2026-08-12",
    history_start_kind: "validation",
    base_date: "2026-08-12",
    status: "accumulating",
    target_size: 100,
    breadth: 0,
    volatility_30d: 0,
    history: []
  }
];

export const fixtureConstituents: Record<string, Constituent[]> = Object.fromEntries(
  fixtureIndexes.map((index) => [index.code, []])
);
